name: .NET

on: [push]

env:
  DD_CIVISIBILITY_AGENTLESS_ENABLED: "true"
  DD_SITE: "datadoghq.com"

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code      

    - name: Setup .NET Core SDK 6.0
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.*

    - name: Setup .NET Core SDK 3.1
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 3.1
        
    - name: Setup .NET Core SDK 2.1
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 2.1

    - name: "Install dd-tool"
      run: dotnet tool install -g dd-trace

    - name: Install dependencies
      run: dotnet restore Datadog.Sketches.sln

    - name: Build
      run: dotnet build Datadog.Sketches.sln --configuration Release --no-restore

    - name: Test
      run: dd-trace ci run --dd-service=dd-sketch-dotnet --dd-env=ci -- dotnet test Datadog.Sketches.sln --configuration Release --no-restore --no-build --verbosity normal
 
